### ISSUE TITLE
Etiquetas con links

### ISSUE THREAD

**Issue by rosa2** [AjuntamentdeBarcelona/decidim.barcelona#182]
Hola y felicitaciones por la herramienta. Me encanta que se visualice la colaboración entre Madrid y Barcelona.

Cada propuesta tiene las etiquetas a que pertenece, pero estás no tienen link para poder rápidamente visualizar todas las propuestas incluidas. En algunos casos se pueden acceder a través de las opciones de la columna izquierda, pero al ser una página larga es incomodo.

Muchas gracias y endavant!

**Comment by beagleknight** [comment]
Hola @rosa2 !
La verdad es que tienes toda la razón :smile: Hemos pensado en añadir ese enlace que nos comentas para que muestre la lista de propuestas filtrada con esos parámetros :+1:
