### ISSUE TITLE
Visibilizar "busca antes de proponer" para hacer la herramienta más eficiente

### ISSUE THREAD

**Issue by rosa2** [AjuntamentdeBarcelona/decidim.barcelona#183]
Hola de nuevo

Al igual que pasa en Madrid, muchas propuestas son duplicados. Creo que es interesante hacer ver a la gente que una forma de optimizar sus respuestas es buscar primero y apoyar. También sirve para crear comunidad con los comentarios. 

Entre las posibilidades que veo están:
- Poner un baner en la parte superior anunciándolo
- Poner un vídeo de uso de la herramienta. Os recomiendo para hacerlo RecordMyDesktop en Gnu/Linux. Entre las cosas que se pueden contar, estaría las ventajas de buscar antes de publicar.
- En la columna de la izquierda, el buscador encima de crea una propuesta y una minifrase para motivar, tipo "¿Seguro que no está ya?"

Por otro lado, los moderadores podrían unir propuestas donde los puntos se sumasen, naturalmente controlando que no sean del mismo autor.

Si este no es el sitio para hacer este tipo de propuestas, por favor, indicadme donde.

Gracias de nuevo por la herramienta

**Comment by mrcasals** [comment]
StackOverflow.com utilitza un sistema que potser es podria aplicar aquí: quan obres un tema nou i comences a escriure el títol, busca altres temes ja existents per semblança. D'aquesta manera es dóna visibilitat als temes ja existents. Potser es podria crear un sistema semblant tenint en compte les àrees d'acció i les categories, també.

**Comment by albertvp** [comment]
Es podria reutilitzar el cercador de propostes a la pàgina de creació, és a dir que mentre s'escriu el nom de la nova proposta apareixi (també asíncronament) el títol de propostes existents a la dreta substituint les recomanacions. D'aquesta manera veus in-situ si n'existeixen de duplicades.

**Comment by andreslucena** [comment]
Gracias a todas por las ideas y el feedback. 
En Consul (el proyecto base de Participación de Madrid) estan aplicando y esutdiando varias formas para solucionar esto: https://github.com/consul/consul/issues/599 
A nivel tecnico, sería hacer un cherry-pick/patch de los commits de Consul que nos interesen.

**Comment by josepjaume** [comment]
Gracias por vuestras aportaciones - vamos a reimplementar esto en la reescritura de `decidim.barcelona` :)
