### ISSUE TITLE
API pública per veure les propostes i poder fer visualitzacions i altres

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim.barcelona#187]
Perquè les dades públiques han de ser explorables.

**Comment by albertvp** [comment]
:+1:
relates to https://github.com/consul/consul/issues/714

**Comment by elaragon** [comment]
Hola,

He visto que ya se dispone una API de propuestas en https://decidim.barcelona/api/proposals.json :+1:  :+1: 

Me gusta mucho que las queries empleen los mismos parámetros de filtrado, ordenación y paginado de la web (resulta muy intuitivo).

No obstante, no encuentro la posibilidad de extraer los comentarios dada una propuesta. Encuentro esto muy importante ya que también son datos visibles y poseen un gran interés por la componente discursiva de esta plataforma. 

Un saludo

**Comment by josepjaume** [comment]
@elaragon no tenemos aún API de comentarios, pero está en nuestro roadmap a corto plazo. Iremos informando a medida que avancemos. La idea es documentarlo todo con Swagger o similar, así que ten en cuenta que Things Can Break ™

**Comment by elaragon** [comment]
@josepjaume fantástico, gracias por el currazo :smile:

**Comment by elaragon** [comment]
IINM en la nueva versión de Decidim sigue funcionando la API de propuestas pero no así la de comentarios, e.g.:
- OK https://decidim.barcelona/api/proposals/100.json
- KO https://decidim.barcelona/api/meetings/100.json

También imagino que tocará repensar la API ahora que hay varios procesos (la v1 estaba diseñada sólo para el PAM).

**Comment by josepjaume** [comment]
@elaragon estamos reescribiendo el proyecto en https://github.com/codegram/decidim . Está [previsto tener una API GraphQL](https://github.com/codegram/decidim/pull/140) con la que creo que vas a estar súper contento ;).

Si no sabes cómo va GraphQL, echale una ojeada a esta demo y flipa:

https://goo.gl/BD6YXB

**Comment by elaragon** [comment]
Muy fan, el salto cualitativo en términos de open data será indescriptible 👏 👏 👏

**Comment by josepjaume** [comment]
Pues dalo por hecho ;)

**Comment by josepjaume** [comment]
Además es auto-documentada, y si cometes un error en la petición, te corrige automáticamente. ¿Has probado de desplegar la pestaña de Docs?

**Comment by josepjaume** [comment]
Closing as we'll create a full-fledged GraphQL API for `decidim-next`.
