### ISSUE TITLE
Netejar "pending tests"

### ISSUE THREAD

**Issue by beagleknight** [AjuntamentdeBarcelona/decidim.barcelona#195]
There are a few tests marked as pending because they are failing randomly. I suggest to create a separate branch to isolate them. I think some of them can be removed or converted to unit tests especially the comments notifications.

Alguns tests estan marcats com a "pending" ja que estan fallant de manera aleatòria. Suggereixo crear una branca separada per aïllar-los. Crec que alguns poden ser eliminats o convertits a unit tests - especialment les notificacions de comentaris.

**Comment by josepjaume** [comment]
Closed in #262
