### ISSUE TITLE
Filtre col·laboratiu basat en l'algorisme Slope One

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim.barcelona#204]
Un filtrat col·laboratiu ens ajudaria a millorar la qualitat de les propostes a la portada, i a ensenyar a un usuari un feed de propostes personalitzat.

Documentació:
https://github.com/ashleyw/Slope-One

**Comment by beagleknight** [comment]
He fet una implementació senzilla del motor de recomenacions aquí #219 
Jo crec que de moment pot servir com a base per a futures ampliacions. Probablement no és tant sofisticat com el Sope-One i es pot optimitzar però penso que ara per ara pot funcionar molt bé.
