### ISSUE TITLE
Paginació infinita

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim.barcelona#215]
Tenir paginació infinita a la portada facilitaria seguir explorant propostes.

**Comment by albertvp** [comment]
@josepjaume et refereixes a la secció de propostes?
Ho sabria fer amb la API JSON per fer les crides asíncrones sense turbolinks.
Si no està prevista en breus es podria mirar d'integrar: https://gist.github.com/cpuguy83/5084883

**Comment by josepjaume** [comment]
@albertvp a mig termini, intentarem passar tota la llista a una API JSON + React. A curt, crec que el desitjable seria implementar-ho tal amb un scroll watcher tal com ho fa:

https://github.com/AjuntamentdeBarcelona/decidim.barcelona/blob/master/app/assets/javascripts/components/proposal_filters.es6.jsx#L11

utilitzant el servei:

https://github.com/AjuntamentdeBarcelona/decidim.barcelona/blob/master/app/assets/javascripts/services/filter_component_service.es6.jsx#L1

**Comment by andreslucena** [comment]
Ja podem tancar això, no?
