### ISSUE TITLE
Unvoting or removing support feature request

### ISSUE THREAD

**Issue by xabier** [AjuntamentdeBarcelona/decidim.barcelona#218]
Unvoting or unsupporting a proposal is a very important feature, we otherwise rest value to the discussion. The comments and debates within proposals should have the potential effect of changing people's mind about their support for the proposal. I suggest we include the option to remove support. This is critical to the very concept of [deliberative democracy](https://en.wikipedia.org/wiki/Deliberative_democracy)

**Comment by josepjaume** [comment]
:+1:

**Comment by xabier** [comment]
It would be good to have this feature ready before the end of PAM-PAD, some users might want to modify their votes.
