### ISSUE TITLE
Invite friends - feature request

### ISSUE THREAD

**Issue by xabier** [AjuntamentdeBarcelona/decidim.barcelona#221]
We can now share proposals with social media but the number of registered users is critical to the performance and quality of the platform. One way to increase the number of registered people is through invitations. We might improve it by adding the option to invite 5-10 people to join the platform. The goal is to make those users that are already familiar with the platform suggest who else (friends, family, co-workers) might be interested on joining. A direct invitation could then be sent from the platform, directly forwarding them to the sign-in page and avoiding the big loss of users that don't even get to the sign-in page when visiting the site. Also a direct, personal invitation from a friend has higher succes rate of signing and involving user than what the media coverage or a direct visit could elicit. I would try to avoid access to full list of contacts (like most of the over-aggresive social media platforms usually do). It would be simply a box to add 5-10 email addresses directly selected by the user. Also badges could be introduced to reward users for their rate of bringing people in.

**Comment by josepjaume** [comment]
I like this very much. :+1:

**Comment by josepjaume** [comment]
Referenced in: https://github.com/codegram/decidim/issues/164
