### ISSUE TITLE
Propostes relacionades

### ISSUE THREAD

**Issue by albertvp** [AjuntamentdeBarcelona/decidim.barcelona#224]
Poder "recomanar" altres propostes que es relacionen per categoria i/o títols semblants.
Pot ser que tractin sobre el mateix però que es proposin coses diferents, si bé no són duplicades la interpretació o el to pot diferir i perdre suport.

**Comment by beagleknight** [comment]
Hola @albertvp ! Actualment estem treballant en un motor de recomenacions, pots veure el seu desenvolupament aquí #219 
Quan tinguem una versió beta funcionant podríem mirar d'afegir altres criteris de recomenació com els que comentes.

**Comment by albertvp** [comment]
:+1:
