### ISSUE TITLE
Bug traduccions

### ISSUE THREAD

**Issue by albertvp** [AjuntamentdeBarcelona/decidim.barcelona#225]
Tot i especificar la locale com a querystring (locale=ca) de vegades mostra text en castellà:

```
<span class="label-proposal">Propuesta de actuación</span>
```

i també als badges de les categories: 

```
<a class="proposal-city" href="/proposals?filter=source%3Dofficial">
        <span class="bcn-icon-localitzacio bcn-icon"></span>
        Toda la ciudad
</a>
```

https://decidim.barcelona/proposals?locale=ca

**Comment by josepjaume** [comment]
Això és culpa d'un abús de caché:

https://github.com/AjuntamentdeBarcelona/decidim.barcelona/blob/master/app/views/proposals/_proposal.html.erb#L4

Com veus, no estem tenint en compte que `I18n.locale` forma part de la clau del cache, i per tant, s'està guardant en la locale del primer usuari que ho veu.

Seria inclús plantejable treure la caché totalment.

PR welcome!! :)

**Comment by andreslucena** [comment]
Ya está aplicado en producción, @albertvp si ves que no es es el caso reabrimos el ticket.

**Comment by andreslucena** [comment]
Gracias por el aviso!
