### ISSUE TITLE
Docs needed

### ISSUE THREAD

**Issue by albertvp** [AjuntamentdeBarcelona/decidim.barcelona#226]
I'd like to contribute by improving responsive layout & javascript to resolve related issues but I need more info.
Found https://www.consul.io/docs/ but no front-end docs provided.
PS: I will learn ruby and inspect current code...
Thanks for the project!

**Comment by josepjaume** [comment]
@albertvp thanks, that would be really helpful!

The `consul` project you've posted for is from HashiCorp, it's a key-value distributed database, nothing to do with http://github.com/consul/consul :)

Unfortunately there are no docs regarding styles / responsive. All I can say is we use [Foundation 5](http://foundation.zurb.com/sites/docs/v/5.5.3/components/grid.html)

Most of the app uses a mixed approach: Either [putting class names on the layout](https://github.com/AjuntamentdeBarcelona/decidim.barcelona/blob/master/app/views/layouts/_header.html.erb#L4) or [SASS mixins](https://github.com/AjuntamentdeBarcelona/decidim.barcelona/blob/master/app/assets/stylesheets/barcelona/_proposals.scss#L57).

Although `decidim.barcelona` is a fork of `consul`, styles are very different. Most of the particularities of Barcelona's design are in [the barcelona folder](https://github.com/AjuntamentdeBarcelona/decidim.barcelona/tree/master/app/assets/stylesheets/barcelona_ but some of them are in the main styles files.

Thanks for the help and don't hesitate to ask for anything!
