### ISSUE TITLE
Friendly Urls

### ISSUE THREAD

**Issue by albertvp** [AjuntamentdeBarcelona/decidim.barcelona#227]
Habilitar SEO urls traduïdes, enlloc de `/proposals/new` que sigui `/proposta/nova`, p.e.
https://github.com/consul/consul/pull/817
o bé https://github.com/enriclluelles/route_translator

**Comment by beagleknight** [comment]
Perfecte! Jo en el passat havia fet servir aquesta https://github.com/francesc/rails-translate-routes 
Li donaré un cop d'ull a la que has proposat aviam quina s'adapta millor al projecte.

**Comment by josepjaume** [comment]
El problema que hi veig amb aquestes coses és que al final les URLs en diferents idiomes acaben identificant diferents recursos. El problema és per les xarxes socials, llavors (Facebook identifica per URL, de manera que els likes es disgregarien).
