### ISSUE TITLE
Add "too much caps" validation on proposal titles

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim.barcelona#228]
This would prevent users abusing caps on proposals.

**Comment by beagleknight** [comment]
:+1: Nice!

**Comment by josepjaume** [comment]
Let's see what can we use for this.

**Comment by andreslucena** [comment]
Already on master: 

https://github.com/AjuntamentdeBarcelona/decidim.barcelona/pull/272
https://github.com/AjuntamentdeBarcelona/decidim.barcelona/pull/277 

Closing this issue.
