### ISSUE TITLE
Gamification with user badges

### ISSUE THREAD

**Issue by xabier** [AjuntamentdeBarcelona/decidim.barcelona#265]
Balancing proposal support with number of proposals or comments is important. Also to bring more people into de platform, or enhancing deliberative participation (instead of just voting). We have currently very few options to stir user behaviour towards a higher quality democratic dynamics. Gamifying the platform with badges could provide useful at some point. Badges can be assigned to proposals or to users. This issue only deals with gamifying user behavior, not proposals (which is a very interesting option as well, and totally compatible with that of users, it would involve taking proposals as having a life of its own that is feed by user behaviour, but I leave this posibility for a latter issue or feature request).

Here is a first approximation of how to do it (some of the badges involve features that have not been proposed or implemented yet):
## Some general considerations

Badges for democracy are different from other uses of badges. The very iconography should be carefully designed, military-rankings or employees-badges or consumer-reinforcement are not the goal. 

Also it is important that the underlying badge algorithms be very clear and transparent. As with the front-page discussion #263 we need to specify what the goals are for gamification and devlop the maths accordingly.
### Badges for user-profile completion
- You have completed your profile to a % of  50/60/80/100 [NOTE: right now the profile is relatively simple and empty, but if we increase the profile complexity these badges start to make sense]
### Participatory involvement/recruitment quality badges
- You have invited n/n+x/n+y/n+z users to the platform.
- You have shared n/n+x/n+y/n+z proposals. [NOTE: balancing with privacy is difficult, but clicks to sharing buttons could do]
### Quality of direct democracy
- You have made n/n+x/n+y/n+z new proposals. 
- You supported n/n+x/n+y/n+z proposals [NOTE: we don't have negative voting for proposals, ideally this badge-variable should include how many proposals were evaluated (positively or negatively) by the user]
### Deliberative quality
- You have made n/n+x/n+y/n+z  comments 
- You have voted/evaluated n/n+x/n+y/n+z  comments 
- Your comments have received n/n+x/n+y/n+z positive votes or positive-negative votes
- Your comments have n/n+x/n+y/n+z replies
- Your proposals have n/n+x/n+y/n+z comments
### Consensus quality
- The proposals you supported gained n/n+x/n+y/n+z supports
- The comments that you voted positive were voted positive n/n+x/n+y/n+z times - the comments that you voted positive were voted negative n/n+x/n+y/n+z times 
- The comments that you voted negative were voted negative n/n+x/n+y/n+z times -  the comments that you voted negative were voted positive n/n+x/n+y/n+z times 
## How to use badge-variables

Badge-variables can be used to generate badges individually or in combination. 

The parameters n, x, y, z define the thresholds to get a badge on a category. Fixing the parameters depends on what needs to be promoted to improve the quality of the democratic process. So, for instance, if the user/proposal ratio is very low and the platform has very few new proposals, n or x,y,z for proposals can be lowered. These parameters should be modified during the lifetime of a participatory process with clear and transparent goals in mind. Users will be notified of what and how much they have to do to gain the next badge. Online-community research has shown that users will tend to make an effort to gain badges that are close to their current state. This way user behaviour can stirred or promoted to increase the democratic quality of the process.
### Single variable badges

It is easy to see how variables can generate badges: there is a badge for n, another for n+x, another for n+y etc.
### Multi-variable badges and promotion profiles

But we can also combine the variables. So, for instance, we could define a number of categories of user-profiles that improve the democratic quality of the platform in increasing order: **district-walker** (only visits ocasionally and supports some proposals of her district), **city-walker** (only visits ocasionally and supports some proposals of the whole city), **district-leader** (her proposals and comments on the district have high quality index), **subject-expert** (has many proposals and high deliberative capacity) or **democracy-recruiter** (has invited many people and shared many proposals online).

**Comment by mrcasals** [comment]
I like the idea of using gamification, but instead of rankings this could be implemented through achievements. See the [Skyrim Steam achievements page](http://steamcommunity.com/stats/TheElderScrollsVSkyrim/achievements) for an example. Instead of showing the rank of the user, we could show the number of achievements the user has unlocked. 

If a levels system is desired, we could calculate the levels with the amount of achievements unlocked, the number of proposals the user has created and/or how many times the user has voted/commented someone else's proposal.

**Comment by xabier** [comment]
I wasn't particularly thinking on ranking the people. I agree that the concept of achievements is much better. In fact, a badge is an achievement.

**Comment by xabier** [comment]
@mrcasals I think stackexchange badges are a good model to follow, less complex of course (at least to start with) https://webmasters.stackexchange.com/help/badges

**Comment by josepjaume** [comment]
This is a really good source of information to be taken into account on `decidim-next`. I've referenced the issue: https://github.com/codegram/decidim/issues/163
