### ISSUE TITLE
Home: Add video slideshow with testimonial videos

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#302]

**Comment by andreslucena** [comment]
The videos to add are: 
- Mercats: https://youtu.be/_RCslt3M6is
- Lluita contra la pobresa: https://youtu.be/Gus0e_KJE4Y
- Escola i mercats: https://youtu.be/P8a_MX2p3mI
- Transport: https://youtu.be/nlpPkrLQBoE
- Dones: https://youtu.be/K9FKTZgIQsM
- Emprenedors: https://youtu.be/6r_Bifc84zE
- Ocupació: https://youtu.be/N3OQAbgoMGY
- Neteja: https://youtu.be/pmFI_EqA5A4
- Turisme: https://youtu.be/Tlyi_zHjmBM
- Espai públic: https://youtu.be/pKXB1W44LUc
- Gent gran: https://youtu.be/ssH0Md5ejZ0
