### ISSUE TITLE
Add "follow a proposal" button in a proposal page

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#308]
When you follow a proposal automatically you are subscribed to a proposal and you recive an email notifications when:
- Someone comment on the proposal
- There is any update to the proposal in the evalution proposals stage.

The follow button it turns to unfollow button 
In the user page it should list all the proposals that the user is subscribed with a checkbox

Follow button text:
[ca] - Segueix aquesta proposta
[es] - Sigue esta propuesta
[en] - Follow this proposal

Unfollow button text:
[ca] - Deixar de seguir aquesta proposta
[es] - Dejar de seguir esta propuesta
[en] - Unfollow this proposal

The email contains the following text:

[ca] - [nom d'usuari] ha comentat la proposta [títol de la proposta + link a la proposta] que segueixes a decidim.barcelona. Veure més propostes [link a la página de propostes]. Deixar de seguir aquesta proposta [unfollow]
[es] - [nom d'usuari] ha comentado la propuesta [títol de la proposta + link a la proposta] que sigues en decidim.barcelona. Ver más propuestas [link a la página de propostes]. Dejar de seguir esta propuesta [unfollow]
[en] - [nom d'usuari] has commented the proposal [títol de la proposta + link a la proposta] that you follow in decidim.barcelona. To see more proposals [link a la página de propostes]. Unfollow this proposal [unfollow]

**Comment by josepjaume** [comment]
Nice idea, moved to the rewrite: https://github.com/codegram/decidim/issues/165
