### ISSUE TITLE
Fix the citizen proposal filter in the proposals page

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#314]
The citizens proposals filter show also city council proposals. It should show just de citizen proposals.

**Comment by josepjaume** [comment]
Are you sure? I don't see this happening

**Comment by josepjaume** [comment]
Closing it for the moment unless we can reproduce it.

**Comment by arnaumonty** [comment]
[Check this](https://decidim.barcelona/proposals?_=1456757638709&filter=source%3Dcitizenship&page=239&turbolinks=true) @josepjaume

**Comment by beagleknight** [comment]
It's not happening on development so I think it's a cache issue. What do you think @josepjaume ?
