### ISSUE TITLE
Modify header of proposals page

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#323]
![propostes](https://cloud.githubusercontent.com/assets/111746/13563186/eaaa8160-e43f-11e5-82b4-7fbe3f6fcbdf.png)

**Comment by arnaumonty** [comment]
@josepjaume find attached the last design with tabs.

**Comment by josepjaume** [comment]
Somehow didn't upload :D

**Comment by arnaumonty** [comment]
@josepjaume Here the text:

[ca]

Aquí pots navegar per les propostes que el Govern ha elaborat per al Pla d'actuació municipal 2016-2019. A aquestes propostes se sumen d’altres que provenen d’iniciatives ciutadanes, d’espais de debat o de propostes realitzades per entitats i organitzacions. Abans de fer-ne una de nova, mira quines propostes hi ha. D’aquesta manera podràs participar amb més coneixement en el debat ja iniciat, donar suport a les propostes que creguis convenients i, finalment, fer-ne de noves si creus que cap de les que hi ha recull allò que vols proposar. Llegeix, opina i participa-hi!

[es]

Aquí puedes navegar por las propuestas que el Gobierno ha elaborado para el Plan de Actuación Municipal 2016-2019. A estas propuestas se suman otras que provienen de iniciativas ciudadanas, de espacios de debate o de propuestas realizadas por entidades y organizaciones. Antes de elaborar una nueva, mira qué propuestas hay. De esta manera podrás participar con mayor conocimiento en el debate ya iniciado, apoyar las propuestas que creas convenientes y finalmente decidir crear otras nuevas, si consideras que ninguna de las existentes incluye lo que deseas proponer. ¡Lee, opina y participa!
