### ISSUE TITLE
Replace the "Comentaris" for "Arguments"

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#330]
- Arguments [ca]
- Argumentos [es]
- Arguments [en]

Replace in the proposal page too.

**Comment by beagleknight** [comment]
@arnaumonty do you mean replacing the word on the whole page? Like: "Sense comentaris" => "Sense arguments" and so on.

**Comment by arnaumonty** [comment]
Yes!

**Comment by josepjaume** [comment]
Still relevant. Let's discuss it here: https://github.com/codegram/decidim/issues/160
