### ISSUE TITLE
Open debates functionality

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#332]
- [ ] Only the official position can create a debate
- [ ] Hide in favor and against votes
- [ ] Add the picture field in the form and apply the design.
- [ ] Apply the "call to debate" design from the home 

![debats](https://cloud.githubusercontent.com/assets/3855859/13523433/bac87e58-e1f5-11e5-9dd1-6b9186c1eb94.png)

![captura_debates](https://cloud.githubusercontent.com/assets/3855859/13603561/6a6bd13e-e53e-11e5-8555-022781885d44.PNG)

**Comment by josepjaume** [comment]
@arnaumonty do you have a design for this?

**Comment by josepjaume** [comment]
Work is being done here: https://github.com/AjuntamentdeBarcelona/decidim.barcelona/pull/334
