### ISSUE TITLE
Add the label "dynamizer" and hide the name when who publish a comment has the dynamizer role

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#351]
This is just for the comments sections on a determined proposal. 

The label in 3 languages
- [ca] dinamitzador/a
- [es] dinamizador/a
- [en] dynamizer

It is a good way to amend a proposal from a meeting.

**Comment by xabier** [comment]
Instead of "dynamizer" I think the right translation is "Facilitator"

On 08/03/16 13:03, Arnau wrote:

> This is just for the comments sections on a determined proposal.
> 
> The label in 3 languages
> - [ca] dinamitzador/a
> - [es] dinamizador/a
> - [en] dynamizer
> 
> It is a good way to amend a proposal from a meeting.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AjuntamentdeBarcelona/decidim.barcelona/issues/351.

## 

wget -O - http://sindominio.net/~xabier/xabier.gpg.asc | gpg --import

```
               xabier BARANDIARAN   |  http://www.barandiaran.net
```

"There is no need for fear or hope, but only to look for new weapons"
                                                              DELEUZE
