### ISSUE TITLE
Sassc: File to import not found or unreadable

### ISSUE THREAD

**Issue by gmfsab** [AjuntamentdeBarcelona/decidim.barcelona#405]
I have some issues regarding the configuration of the app. I'm not deploying it at Heroku so far, but in a remote virtual machine with Ubuntu 14.04 Server.

After installing the master branch's bundle, a TCP socket is created with Puma and Nginx sets up a proxy that makes remote connections. However, both in development and testing evironments, the following error message appears when a client tries to load the application:

```
SassC::SyntaxError in Welcome#index 

Error: File to import not found or unreadable: bundle
       Parent style sheet: /home/suport/decidimbcn/app/assets/stylesheets/application.scss
        on line 20 of app/assets/stylesheets/application.scss
>> @import "bundle";
   ^
```

```
Extracted source:
 <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title><%= content_for?(:title) ? yield(:title) : Setting['org_name'] %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_google_maps_api_tag %>
    <%= render partial: 'layouts/i18n' %>
```

In production environment, the app works but with no styles. 

It’s possible that it was a known issue, but I'm getting confused.  What can or what should I do to solve this?

**Comment by andreslucena** [comment]
Hi @gmfsab. I think it's a problem related with webpack. 

Have you tried with the docker-compose commands that we have on the README?

**Comment by andreslucena** [comment]
@beagleknight could you check this issue please?

**Comment by beagleknight** [comment]
Hi there @gmfsab!

@andreslucena is correct. The problem is rails cannot find the bundle.js file which is compiled using webpack. You can install webpack using npm like `npm install -g webpack` and then install npm local dependencies using `npm install`.

Finally you can run the build using `webpack --watch --colors`.

If you are using `docker-compose` the service is automatically started using `docker-compose up` command.

Cheers!

**Comment by andreslucena** [comment]
@beagleknight could we update the README instructions (Configuration for development and test environments) with this?

**Comment by josepjaume** [comment]
That was done looong ago 🎉
