### ISSUE TITLE
Create an admin panel for Participatory Processes

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim.barcelona#473]
We should enable a panel in the admin section that allows us to create, modify and delete Participatory Processes.

**Comment by beagleknight** [comment]
I created a PR for this #477 . I'm not sure about deleting a Participatory Processes. It sounds very dangerous to me... maybe we can hide or disable them?

**Comment by beagleknight** [comment]
@josepjaume Since the PR is merged this can be closed, right?
