### ISSUE TITLE
Terms and conditions shouldn't be scoped to a participatory process

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim.barcelona#500]
Currently, the [Terms and Conditions](https://decidim.barcelona/pam/conditions) page is scoped to a participatory process.

It should be moved back to the root level, and all the links should be updated accordingly.

**Comment by beagleknight** [comment]
This should be applied to the "Information" page as well, isn't it @josepjaume ?

**Comment by andreslucena** [comment]
@beagleknight yes, it should be general for decidim. 

Related to this, actually this "information" page is being rewritten on two pages, one general for decidim and another one specific for this PAM process.

**Comment by beagleknight** [comment]
I just forced the terms and conditions link to don't use a participatory process id. I want to use a better approach in the `rebranding` branch where we have a real participatory scope.
