### ISSUE TITLE
Add pictures to Participatory Processes

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim.barcelona#507]
Show pictures in `Participatory Processes`, using the same admin interface as files. We can upload mixed files in there and show each of them as appropiate (pictures in a slideshow, any other kind of file as downloadable).

We're already making the `documents` vs `images` distinction at the decorator level: https://github.com/AjuntamentdeBarcelona/decidim.barcelona/blob/master/app/decorators/participatory_process_decorator.rb#L29

We probably need to define image size transformations at the uploader as well.

**Comment by andreslucena** [comment]
Closing on favor of https://github.com/decidim/decidim/issues/1266
