### ISSUE TITLE
Hashing for proposals and results

### ISSUE THREAD

**Issue by xabier** [AjuntamentdeBarcelona/decidim.barcelona#551]
In order to avoid manipulation of results or proposal contents we should include some kind of hashing for proposals. The hashing information should include title, author, content, url and date. It should be automatically generated when the proposal is uploaded and make visible. Small hash displayed below the proposal on its page. Version control and history tab should be added in a second improvement (but this needs more working).

**Comment by josepjaume** [comment]
This is a good idea to implement at `decidim-next`, and I've created an issue to discuss that: https://github.com/codegram/decidim/issues/162
