### ISSUE TITLE
Substitute Google Analytics by Free/Open Alternative

### ISSUE THREAD

**Issue by xabier** [AjuntamentdeBarcelona/decidim.barcelona#552]
We need a data analytics engine that is not Google Analytics, we should test a good configuration of Piwik or other free/open alternative. We also need to download Google Analytics dataset to feed the new engine and keep a coherent record.

**Comment by josepjaume** [comment]
This will happen on decidim-next. It's been put in the `ideas` bucket: https://github.com/codegram/decidim/projects/4
