### ISSUE TITLE
CSS error on steps

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#570]
There is a bug with the horizontal bar on the right. 

![seleccio_460](https://cloud.githubusercontent.com/assets/717367/19524918/9b3e2252-961f-11e6-9c1e-9e99f0388727.png)

**Comment by josepjaume** [comment]
This is a CSS bug and should be fixed in decidim-design first. Same as in #571

**Comment by josepjaume** [comment]
It turns out it was my fault as I forgot to include the carousel code. Fixed in #579
