### ISSUE TITLE
Steps broken on 5 steps

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#571]
If I put 5 steps on a ParticipatoryProcess then the CSS breaks (on Firefox 48.0). 

![seleccio_461](https://cloud.githubusercontent.com/assets/717367/19524994/dc995d84-961f-11e6-951a-b6cf21e85d57.png)

**Comment by josepjaume** [comment]
This is a CSS bug and should be fixed in `decidim-design` first.

**Comment by josepjaume** [comment]
This got fixed in #579
