### ISSUE TITLE
Fix meetings CSS

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#581]
The map doesn't show with the same design and the infoboxes don't work. 

https://decidimbcn-next-staging.herokuapp.com/pam/2/meetings?filter=date=past

**Comment by josepjaume** [comment]
Reference: http://decidim-design.marsbased.com/phase1_meetings/

We should avoid using the small `type` labels on top of the meetings, as they are a resource to be used when mixed content is shown (proposals, meetings and action plans mixed together, for example).
