### ISSUE TITLE
CSS highlight on debates with regidors

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#585]
It isn't highglighted: https://decidimbcn-next-staging.herokuapp.com/pam/2/debates/decidim-amb-ada-colau-sobre-el-futur-de-la-ciutat

**Comment by beagleknight** [comment]
Hi @andreslucena ! What is supposed to be highlighted? :thinking:

**Comment by beagleknight** [comment]
Do you mean the badge or something? :open_mouth: Can you upload a screenshot please? @andreslucena

**Comment by andreslucena** [comment]
It's missing the  comment--highlight class

On the mockup: 

![seleccio_486](https://cloud.githubusercontent.com/assets/717367/19765160/35ca127c-9c47-11e6-9acf-22dc3e460d24.png)

On production: 

![seleccio_485](https://cloud.githubusercontent.com/assets/717367/19765164/38dc899a-9c47-11e6-87ed-c67444b3bb84.png)

It isn't prioritary right now.
