### ISSUE TITLE
Padding on filters on Proposals

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#587]
It's missing when I enter the first time, when I change the filter it's fixed. 

![seleccio_462](https://cloud.githubusercontent.com/assets/717367/19551618/60192306-96ac-11e6-9b54-8e02b9c67e35.png)

**Comment by josepjaume** [comment]
@beagleknight maybe we could finally implement the dropdown?

**Comment by beagleknight** [comment]
@josepjaume Sure.. np. On it!
