### ISSUE TITLE
Proposals from meetings don't have a valid user 

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#588]
It appears as "no user". It should be "Cites presencials"

**Comment by beagleknight** [comment]
@andreslucena What about removing the "no user" label instead of assuming that name? The problem is the "no user" appear when the user has been deleted.

**Comment by andreslucena** [comment]
:+1: for the moment we can have it like that (showing nothing on proposals that comes from a meeting)
