### ISSUE TITLE
Choose the primary component (opened by default) in each step

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#593]

**Comment by josepjaume** [comment]
This can be tricky. Definitely an improvent for `decidim-next` as we don't have the notion of `component`. Also, I think trying to find a solution for the navigational issues we have is going down the rabbit hole - we have to find a global way to solve it.

@andreslucena thoughts?

P.D. Closing the issue by now, unless we find it urgent.
