### ISSUE TITLE
New Flag: Proposal creation and comment without vote

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#607]
We need a new kind of Flag for the new ParticipatoryProcesses next week. It should have the following settings: 
- User can create Proposals
- User can comment on Proposals
- User can't vote on Proposals 
- Proposal form don't have PAM message (" S'està estudiant la viabilitat d'aquesta proposta i la possible inclusió al Pla Municipal 2016-2019....")
- Proposal form don't have scope (City/Districts)
- Also it would be nice if we can have the new Proposal form design. 

I don't know if it should be a new Flag or some configuration on pre-existent flag.

**Comment by beagleknight** [comment]
@andreslucena I think it's better to split this in two flags:
- **proposal_without_votes**: You can create and comment proposals. You can't vote proposals.
- **proposal_without_scope**: You can't assign scope (city/district) to proposals. Scope filters are hidden.

What do you think?

**Comment by beagleknight** [comment]
About the PAM message I think we should create another issue to remove this message. I think it's not related to flags or permissions.

**Comment by josepjaume** [comment]
I would use `enable_proposal_votes` and `enable_proposal_scope` as flag names.

**Comment by andreslucena** [comment]
Yes, the PAM message has another issue already #674 

+1 to both flags
