### ISSUE TITLE
Review subcategories validations on resource (Proposal, Meeting, etc) 

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#615]
Some ParticipatoryProcesses don't have subcategories. It should be possible to save a Meeting or a Proposal without a giving subcategory. Right now there is this error on save _"Subcategory no pot estar en blanc"_

**Comment by josepjaume** [comment]
I don't think we can do that, as the relationship between proposals and categories are done via the `subcategory`. I'd try to find a workaround for that, like having a single category and hiding it on the pickers and filters.

**Comment by andreslucena** [comment]
Ok, I think that would be fine as a solution. For the moment that's what we're doing with the new processes (creating a dummy subcategory).
