### ISSUE TITLE
Better error page on invalid confirmation token

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#617]
When a user receives the registraton email and clicks on an invalid confirmation link it gets a 500 error: 

> undefined method `encrypted_password' for nil:NilClass

**Comment by andreslucena** [comment]
Uops I think it was an error on my side, that I had copied wrong the confirmation token.

The issue actually is that when a user register and puts a wrong confirmation token it gets a 500 instead of getting a more user friendly error page. 

```
undefined method `encrypted_password' for nil:NilClass
app/controllers/users/confirmations_controller.rb:35:in `show'
```

It has very low priority.

**Comment by josepjaume** [comment]
Closing this as it's a nice to have. Probably better discuss this feature on `decidim-next`.
