### ISSUE TITLE
Review alerts and callouts 

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#618]
On multiple forms (proposals new, meeting edit, sign up, new user, etc) it still have the old styles (alert) and it doesn't show properly, generating a big usability issue 

![seleccio_467](https://cloud.githubusercontent.com/assets/717367/19597032/55bce42e-9792-11e6-923e-ba2d6fd7e746.png)

**Comment by beagleknight** [comment]
Hi @andreslucena ! I'm not following you :D. The screenshot provided is showing the new callout, isn'it?

**Comment by andreslucena** [comment]
There are 2 alerts on this page, the first one is OK, the second is practically invisible: 

![ynvujbvl2s](https://cloud.githubusercontent.com/assets/717367/19637190/046aa7a8-99ce-11e6-8205-d798bdc577e9.png)
