### ISSUE TITLE
Invalid i18n on new invalid session

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#622]
When I go to new session and the password is bad I get: 
translation missing: ca.devise.failure.user.invalid 

It should have the message "wrong email or password"

**Comment by beagleknight** [comment]
Hi @andreslucena I tested it both on local and production and it looks ok to me.

![2016-11-02_14 30 25_1920x1980](https://cloud.githubusercontent.com/assets/106021/19930509/149ffb72-a109-11e6-9007-d830de355ea8.png)

**Comment by andreslucena** [comment]
The problem is when it's an existing user that didn't put the right password; the email exists on the database but the pass is wrong.

**Comment by andreslucena** [comment]
Closing as fixed on new version.
