### ISSUE TITLE
Add an empty field in dropdowns by default

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#652]
- [x] To choose a district (in create proposals or meetings forms)
- [ ] To choose a participatory process (in meetings browser)

It is an UX measure but it will reduce the mistakes related to the default field as "Ciutat Vella" in districts

**Comment by beagleknight** [comment]
@arnaumonty I implemented a new dropdown for selecting a participatory process while browsing admin#categories and moderation#meetings here #692 . By default is selecting the first participatory process and both lists displays the correct resources. I think it's not necessary to include a blank option there.
