### ISSUE TITLE
Text editor to modify static pages content as "Information" page or "Terms of use" page

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#662]

**Comment by andreslucena** [comment]
The editor should have an h2 markup, and it should automatically make the sidebar, for pages like conditions or more information.

**Comment by josepjaume** [comment]
Sorry guize, but this will happen on `decidim-next` ;). Re-open the issue if you think it's really important to have at this stage of `decidim.barcelona`.

I've added an idea to the project: https://github.com/codegram/decidim/issues/161

Note: Check out the `planning` project:

https://github.com/codegram/decidim/projects/4
