### ISSUE TITLE
Meetings filter should be passed/filter depending of the process

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#669]
For instance on the PAM process it should have the "passed" filter selected by default, but on the rest of the processes it should have the "next" filter selected. 

It's on a process to process basis so I think we need two flags for meetings: 
- enable_meetings_passed
- enable_meetings_next

(or as you want to call them)

**Comment by josepjaume** [comment]
What about showing the `past` filter by default when there's no future meeting?

**Comment by beagleknight** [comment]
I'm with @josepjaume . If it can be implemented without adding a flag, better.

**Comment by andreslucena** [comment]
> What about showing the past filter by default when there's no future meeting?

Yes, it's enough for the v0.5 ATM

**Comment by josepjaume** [comment]
Implemented it by making future events default - good enough for the moment.

**Comment by andreslucena** [comment]
That works as a temporal friday fix but we at least need the "showing the past filter by default when there's no future meeting" for this version.
