### ISSUE TITLE
Reconfiguring of home page: direct action button for proposals or voting or active phases

### ISSUE THREAD

**Issue by xabier** [AjuntamentdeBarcelona/decidim.barcelona#702]
There is too long a path to reach the active-participatory phase of an ongoing participatory process, we need to add direct link from the front page.

**Comment by josepjaume** [comment]
I would go for adding a `Participate` button the same way it appears on the Participatory Process `index` page:

<img width="388" alt="screen shot 2016-10-30 at 9 08 52 pm" src="https://cloud.githubusercontent.com/assets/111746/19839606/39e3f80a-9ee5-11e6-994c-5b4e7b97f5d2.png">

Still, this long path to the desired action is a direct consequence of the way we defined the steps navigation. There's other issues stemming from this: multiple URLs for the same content, multiple views for the same resource.

I have some ideas that would shorten the path, allowing us to remove the `participate` buttons along the page, and that would the overall UX at the same time - all without changing the steps model or its features.

**Comment by beagleknight** [comment]
I tried to add the button to the participatory processes on the home page:

![2016-11-02_12 31 39_1920x1980](https://cloud.githubusercontent.com/assets/106021/19927097/881820b8-a0f8-11e6-9596-75a9a37f4114.png)

As you can see the current design can't handle these buttons for this layout.
