### ISSUE TITLE
Compartir link-box missing on process page mobile display

### ISSUE THREAD

**Issue by xabier** [AjuntamentdeBarcelona/decidim.barcelona#707]
The third link-box on the process header "Compartir" does not display on mobile
![problem-mobile-decidim](https://cloud.githubusercontent.com/assets/537284/19839363/8d5e08ae-9ee0-11e6-8092-ba16672c9a1a.png)

**Comment by beagleknight** [comment]
Hi @xabier ! I'm checking the website and I can see the link you mentioned. Can you review if the problem persist?

**Comment by josepjaume** [comment]
Closing unless it manifests again.
