### ISSUE TITLE
Add google analytics code

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#710]
On app/views/layouts/_tracking.html.erb we need to change the Google Analytics tracking code to the corporative: 

```

  <script type="text/javascript" charset="utf-8" src="https://w9.barcelona.cat/assets/core/javascripts/core.js"></script>

  <script type="text/javascript">
    bcn.statistics({keys: ['UA-61717963-24','UA-73116847-1'], tgm: true });
  </script>

```

I'm trying to do it on localhost but I get an error on the javascript console: 
> ReferenceError: bcn is not defined

Maybe it's something related with my browser configuration (Firefox 49.0.2). Could you check if it works?

**Comment by beagleknight** [comment]
Hi @andreslucena ! Your google analytics code is very different from the current one:

```
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-73116847-1', 'auto');
    ga('send', 'pageview');
  </script>
```

Are you trying to import the `bcn` variable from the other script? It's not going to work if the script doesn't define the `bcn` variable as a global (binding it to the `window` object).

**Comment by beagleknight** [comment]
@andreslucena  Well... I tried your code and it's working fine on google chrome so it may be related to the javascript engine of each browser.

**Comment by andreslucena** [comment]
Confirmed that's something about my browser. It's probably an addon, I have several for privacy reasons and one of them doesn't like the ajuntament script. 

So, PEBCAK, @beagleknight you can go ahead with this script.

**Comment by beagleknight** [comment]
This should be closed :)
