### ISSUE TITLE
Bug in the meetings related box in a proposal

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#724]
The related meeting in a proposal is not showing correctly

for example: https://decidim.barcelona/revisio-de-la-normativa-de-participacio-ciutadana/52/proposals/el-grau-d-impacte-d-un-proces-participatiu-es-definira-en-el-moment-inicial-del-proces

![el grau d impacte d un proces participatiu es definira en el moment inicial del proces](https://cloud.githubusercontent.com/assets/3855859/19970747/40205c2c-a1dd-11e6-9858-feddfbf88d67.png)

**Comment by beagleknight** [comment]
This should be closed
