### ISSUE TITLE
Solve html code visualitzation 

### ISSUE THREAD

**Issue by JuanLinaresLanzman** [AjuntamentdeBarcelona/decidim.barcelona#727]
Example here:

https://decidim.barcelona/revisio-de-la-normativa-de-participacio-ciutadana/52/proposals/dinamitzar-els-consells

![captura de pantalla 2016-11-07 a las 12 25 59](https://cloud.githubusercontent.com/assets/22983668/20056229/6116b916-a4e5-11e6-9042-57e881de383a.png)

**Comment by andreslucena** [comment]
Duplicated with #724 
I'm closing this one
