### ISSUE TITLE
On Steps graph should use the summary and not the description 

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#733]
Right now the summary isn't used for anything

**Comment by beagleknight** [comment]
Hi @andreslucena !
We are rendering the step graph using a rails partial: https://github.com/AjuntamentdeBarcelona/decidim.barcelona/blob/master/app/views/participatory_processes/_timeline.html.erb#L15

If the `summary` is blank it fallbacks to the description. Can you provide an example where it's not using the `summary` correctly?

**Comment by andreslucena** [comment]
Closing as invalid on new version (we don't have summaries anymore)
