### ISSUE TITLE
This meeting is not showing in the meetings page of the process (Mercat de Sant Antoni)

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#745]
https://decidim.barcelona/moderation/meetings/els-arquitectes-ens-ensenyen-com-sera-el-mercat/edit

**Comment by arnaumonty** [comment]
It seems that could be a problem with the date or a limitation of the number of meeting showing in the meetings grid page

**Comment by beagleknight** [comment]
Yeah, you were totally right @arnaumonty. The number of pages was wrong. I fixed it and also included 16 per page to accommodate the new design.
