### ISSUE TITLE
Proposals voting limited to N amount

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim.barcelona#753]
We need a flag for a new kind of proposal, where a verified user can vote for 10 proposals, for the next phase of Participatory Budgets Pilot on Eixample for the 28th of november. It should be applied to this proposals: https://decidim.barcelona/prova-pilot-pressupostos-participatius/8/proposals?order=random 

Until the next phase, the user can view and change their proposals vote. 

The initial design can be found here: https://decidim-design.herokuapp.com/phase4_proposals_2/ - although it should be improved. 

Further explanation: 

> Durant la fase de deliberació totes les persones empadronades a la ciutat podran prioritzar les propostes, a través d’un sistema de suports.
> Tothom disposarà de 10 suports a repartir entre les diferents propostes d’actuació.

**Comment by andreslucena** [comment]
We're making some tests on the "process prova", and we've detected a few bugs: 
* [ ] When we're allowing votes we shouldn't allow to create new proposals; if we activate the proposals_read_only then we can't vote 
* [x] The support button in the proposal page doesn't works well after give support from the propoosal page. If you remove to vote, you can't vote this proposal again. example: https://decidim.barcelona/procesprova/67/proposals?order=random
* [ ] There should be a link to "View my votes" on the callout of "you've left N votes" (linking to ?filter=interaction=voted ) 
* [ ] If you have proposals and read only flags in other step, the proposal page is linked in the step where you have the flag activated, and you can't give support from there, just from proposals page in the active step. One possible solution is disable the proposals in the passed/old steps, but it isn't recomendable in terms of traceability

**Comment by beagleknight** [comment]
@andreslucena I think the first and the last issues are fixed in #777 so I will implement the third checkbox now.
