### ISSUE TITLE
Replace "Cites presencials" for "Trobades presencials"

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#754]
[Ca] Trobades presencials

[Cas] Encuentros presenciales

[En] Meetings

**Comment by xabier** [comment]
Just "Trobades" and "Encuentros" would be better

**Comment by andreslucena** [comment]
Closing as irrelevant on new version (you can change this name on the admin itself and is depended on the admin's feature setting)
