### ISSUE TITLE
style broking design cookies law warning

### ISSUE THREAD

**Issue by JuanLinaresLanzman** [AjuntamentdeBarcelona/decidim.barcelona#757]
<img width="1242" alt="captura de pantalla 2016-11-22 a las 11 27 29" src="https://cloud.githubusercontent.com/assets/22983668/20520401/f6253fb0-b0a6-11e6-8278-f359ecd3b191.png">

**Comment by andreslucena** [comment]
Closing this issue as fixed with new version.
