### ISSUE TITLE
need catalan translation proposal features

### ISSUE THREAD

**Issue by JuanLinaresLanzman** [AjuntamentdeBarcelona/decidim.barcelona#762]
<img width="1190" alt="captura de pantalla 2016-11-24 a las 10 46 20" src="https://cloud.githubusercontent.com/assets/22983668/20593733/c4a2ede6-b233-11e6-888f-b66600290ab4.png">
 
For example:
"Mostrando 26 propuestas"
"Crear una propuesta"
And more...

**Comment by rosa2** [comment]
Més coses de català:
- al peu de pàgina: software lliure hauria de ser "programari lliure".
- a la url en volta de propossals hauria de ser "propostes"

**Comment by andreslucena** [comment]
Already working on decidim.barcelona. 

> al peu de pàgina: software lliure hauria de ser "programari lliure".

The only missing was this. Thanks! 

> a la url en volta de propossals hauria de ser "propostes"

Discussing on https://github.com/decidim/decidim/issues/919
