### ISSUE TITLE
Imposibilitat de restabliment de la contrasenya

### ISSUE THREAD

**Issue by rosa2** [AjuntamentdeBarcelona/decidim.barcelona#764]
Hola
No he pogut restablir la contrasenya. He provat al SO Ubuntu 14.04 amb Firefox 50.0 i amb Chromium 53.0.2785.143. 
Em dona l'errada 
```
1 error impedir guardar el compte:
Reset password token no és vàlid
```
Ho he intentat com 4 voltes i sempre el mateix. Després revisant el correu he trobat el correu de confirmació del compte i per provar ho he fet servir una altra volta. I he pogut entrar al compte i fer un comentari. No he pogut canviar la contrasenya perquè em demanava l'antiga.

Crec que es bug que amb la confirmació antiga (havia confirmat i fet una proposta) puga tornar a accedir-hi, a més de no poder restablir la contrasenya.

Moltes gràcies per l'aplicatiu :)

**Comment by josepjaume** [comment]
Hola Rosa,

Gràcies per reportar-nos l'errada! He marcat la incidència com a "bug". Intentarem fer-hi un cop d'ull el més ràpidament possible.

Gràcies!

**Comment by andreslucena** [comment]
Hola @rosa2 - pots comprovar-ho ara? En els últims mesos vam migrar la plataforma a la nova versió i crec que ara hauria de funcionar.

**Comment by andreslucena** [comment]
Tanquem aquest issue, si encara tens problemes pots enviar un mail a suport@decidim.barcelona. Gràcies!
