### ISSUE TITLE
"Resum proposta" characters length

### ISSUE THREAD

**Issue by ibruque** [AjuntamentdeBarcelona/decidim.barcelona#766]
The characters length to fill the "Resum proposta" is usually not enought, but I can understand why you limit it to 350 characters. But it would be very useful for the user a counter with the characters you have when you are writting.

**Comment by rosa2** [comment]
This should be also in comments

**Comment by andreslucena** [comment]
Moving this to the new version https://github.com/decidim/decidim/issues/1279 

Closing this issue
