### ISSUE TITLE
Metadecidim: recull de propostes i priorització: on crear propostes i on votar-les

### ISSUE THREAD

**Issue by rosa2** [AjuntamentdeBarcelona/decidim.barcelona#769]
Hola

A priorització de propostes
https://decidim.barcelona/metadecidim/62/proposals?order=random
puc crear propostes i votar
i a recollida de propostes
https://decidim.barcelona/metadecidim/61/proposals?order=hot_score&random_seed=0.27182033612431344
no puc

No sé si el fet de votar en aquesta oportunitat era diferent perquè no tinc l'usuari verificat, però he pogut votar.

**Comment by rosa2** [comment]
Estrany

A
https://decidim.barcelona/metadecidim/62/proposals?order=random
puc crear propostes i votar
i a 
https://decidim.barcelona/metadecidim/61/proposals?order=hot_score&random_seed=0.27182033612431344
no puc

La diferència és 61 o 62 a l'url (he fet proves)

**Comment by rosa2** [comment]
Veig que la diferència és si vas a recollida de propostes (no et deixe) i priorització de propostes (et deixa).
Crec que per un usuari normal és un embolic :)

**Comment by rosa2** [comment]
Veig que després de crear una proposta, t'envia a recollida de propostes (on no pots fer, ni votar propostes).

**Comment by rosa2** [comment]
Al tornar a priorització, puc votar la meva proposta. No seria normal que qui crea una proposta tinga el seu vot automàticament?

**Comment by josepjaume** [comment]
Gràcies per enviar-nos l'issue @rosa2, ho hem marcat com a `bug` i ens hi posarem a treballar el més aviat possible.
