### ISSUE TITLE
Access denied a fitxers pujats

### ISSUE THREAD

**Issue by rosa2** [AjuntamentdeBarcelona/decidim.barcelona#770]
Hola

A https://decidim.barcelona/metadecidim/62/proposals/gamificacio hi han ficat un link de document que dona accés denegat (accés denied)

Vaig a cercar més per si és un cas concret o és general.

**Comment by rosa2** [comment]
Una altra
https://decidim.barcelona/metadecidim/62/proposals/iniciatives-ciutadanes

**Comment by josepjaume** [comment]
Gràcies per notificar-nos de l'errada! Ho posem com a `bug`.

**Comment by beagleknight** [comment]
Hola @rosa2! Gràcies per notificar el problema. 

He revisat l'enllaç que ens havies comentat i resulta que està trencat: https://decidimbcn-production.s3.amazonaws.com/uploads/participatory_processes/metadecidim/file/85/Plan_desarrollo_decidim_v10_151116.pdf està trencat. 

El document correcte hauria de ser: 
https://decidimbcn-production.s3.amazonaws.com/uploads/participatory_processes/metadecidim/file/92/Plan_desarrollo_decidim.pdf

També he arreglat els permissos de AWS perquè doni un error més entenedor.

**Comment by rosa2** [comment]
Hola
Crec que més que trencant és que es va pujar una nova versió del fitxer i l'antic es va esborrar. La persona no va arreglar el link. Hi ha alguna manera de verificar que no passi en això? Si no, s'hauria de fer un nou issue per evitar-ho, no?

Super @beagleknight de posar un missatge més entenedor :)
