### ISSUE TITLE
Geolocalització a Nova York de cites presencials de Metadecidim

### ISSUE THREAD

**Issue by rosa2** [AjuntamentdeBarcelona/decidim.barcelona#772]
Hola
En les següents entrades de Metadecidim la geolocalització és a Nova York

https://decidim.barcelona/metadecidim/61/proposals/modulo-de-seguimiento-y-evaluacion
https://decidim.barcelona/metadecidim/61/proposals/ajudes-a-la-navegacio-per-la-plataforma
https://decidim.barcelona/metadecidim/61/proposals/deteccio-de-propostes-relacionades-i-possibilitat-de-fusionar-les
https://decidim.barcelona/metadecidim/61/proposals/integrar-a-la-plataforma-processos-participatius-a-proposta-de-la-ciutadania
https://decidim.barcelona/metadecidim/61/proposals/introduir-mecanismes-que-afavoreixin-la-participacio-dels-joves
https://decidim.barcelona/metadecidim/61/proposals/diagnostico-de-calidad

**Comment by andreslucena** [comment]
Hola! Crec que era un bug amb la versió antiga del web, ara es veu bé (a Barcelona): https://www.decidim.barcelona/processes/12/f/19/meetings/678
