### ISSUE TITLE
Encriptar emails

### ISSUE THREAD

**Issue by rosa2** [AjuntamentdeBarcelona/decidim.barcelona#773]
Hola

Vaig parlar amb un de vosaltres a metadecidim sobre encriptar emails d'usuaris per protegir-los en cas de hackeig de la base de dades i que a Drupal es pot fer. Per si voleu reaprofitar codis encara que sigui en php

https://www.drupal.org/project/dbee

**Comment by rosa2** [comment]
També interessant per encriptar d'altres dades, com ara les votacions o el nom d'usuari
https://www.drupal.org/project/encrypt

**Comment by andreslucena** [comment]
Migrat a la nova versió: https://github.com/decidim/decidim/issues/1272 
Tanco aquest issue
