### ISSUE TITLE
Piwik

### ISSUE THREAD

**Issue by rosa2** [AjuntamentdeBarcelona/decidim.barcelona#774]
Hola

Com veig que hi ha interès a canviar analytics per pikiw, alguna dada que us pot servir:

-gent que coneixem que ja té instal·lat piwik: [blackhold](https://twitter.com/blackhold_), https://www.woorank.com/en/www/www.guadalinex.net , https://www.woorank.com/en/www/sanidad.democraciarealya.es , https://www.woorank.com/en/www/kde-espana.org , https://www.woorank.com/en/www/arteleku.net
-institucions (per si hi ha que convencé a cap polític o administrador):  [Sede Electrónica del Boletin Oficial de la Comunidad de Madrid](https://www.woorank.com/en/www/w3.bocm.es), [Sede Electrónica Ayuntamiento de Córdoba](https://www.woorank.com/en/www/sede.cordoba.es), [Grupos Locales y Universitarios: Amnistía Internacional España ](https://www.woorank.com/en/www/grupos.es.amnesty.org), [Boletín Oficial del Registro Mercantil](https://www.woorank.com/en/www/libreborme.net) y más que podéis encontrar en la web de woorank.com
-si la pàgina està amb ssl, el servidor també té que ser-hi http://blackhold.nusepas.com/2014/04/13/monitorizar-webs-https-con-piwik/

Com veieu, tinc moltes ganes de veure el canvi ;)

**Comment by rosa2** [comment]
Sobre la migració, m'imagino que ja heu vist https://github.com/piwik/piwik/issues/6095 i la proposta de crowfunding o sponsoring (si l'ajuntament té tot amb GA, a lo millor pot fer eixe sponsoring en volta de pagar per una migració de dades). A lo millor es podria fer una col·laboració entre els ajuntaments de Madrid, Coruña i Barcelona...

Aquest projecte que és obsolet i recomana agafar els logs https://github.com/clearcode/Google2Piwik

Com exportar les dades de GA http://www.stateofdigital.com/exporting-google-analytics-data/ 

També interessant és que aquest any [Cornell University Library is migrating from Google Analytics to Piwik: Why and How](https://proposalspace.com/p/7377/s ) Igual se'ls pot contactar...

**Comment by andreslucena** [comment]
Ja vam migrar a Piwik amb la nova versió. Gràcies!
