### ISSUE TITLE
Errada al fer comentari llarg

### ISSUE THREAD

**Issue by rosa2** [AjuntamentdeBarcelona/decidim.barcelona#778]
Hola

Als comentaris no s'indica un límit de caràcters. Quan fas un comentari massa llarg es queda donant voltes l'animació de les fletxes vermelles i no passa res. Proposo que s'indiqui eixe límit i que arribat al límit no et deixi escriure més, com passe quan fas una proposta.

**Comment by andreslucena** [comment]
Movem aquest issue a la nova versió: https://github.com/decidim/decidim/issues/1279 
Tanco l'issue.
