### ISSUE TITLE
Substitució de Google Tag Manager

### ISSUE THREAD

**Issue by rosa2** [AjuntamentdeBarcelona/decidim.barcelona#780]
Hola
Falte l'alternativa Google Tag Manager que també utilitza la web: https://7tag.org/ i que funcione amb Piwik

**Comment by rosa2** [comment]
https://github.com/QubitProducts/OpenTag

7tag s'ha tornat codi tancat.

**Comment by andreslucena** [comment]
Ja no utilitzem més el Google Tag Manager. 
Per altra banda, a la nova versió de decidim tenim un ghostery d'1 tracker (Piwik on-site). 
Tanco l'issue.
