### ISSUE TITLE
More possible orderings for proposals 

### ISSUE THREAD

**Issue by xabier** [AjuntamentdeBarcelona/decidim.barcelona#781]
This is a small feature and has no urgency but is a nice to have and easy one.

1. By number of comments
2. By times viewed vs. times approved
3. By controversy (and index needs to be defined here, Pablo Aragón can help)

The first would be nice to have and very easy to implement

**Comment by andreslucena** [comment]
Moved this to new repo https://github.com/decidim/decidim/issues/1283 
Closing this issue
