### ISSUE TITLE
chance of "help" for "(more) information" in phase component

### ISSUE THREAD

**Issue by xabier** [AjuntamentdeBarcelona/decidim.barcelona#782]
Phase component ordering has now changed to display by default the components there are actuable. Previously the components that was first shown was the one labeled as more information. I have seen that this component has now shifted to the right and has the name help. This is incorrect and should be corrected although as a help component tooth potentially be interesting the complainant named more information is a proper component and should be there a such. Take into account that in many occasions this component has important information that works as a kind of social contract between city council and citizens and therefore it should not be considered simply help to guide the user on the navigation and functions of the website but rather as a proper component that includes critical information to describe the phase and to describe how the process works.

**Comment by xabier** [comment]
Phase, not face.

**Comment by xabier** [comment]
This is simple and relatively urgent. 
"I'm so ronery"
https://www.youtube.com/watch?v=xh_9QhRzJEs

**Comment by andreslucena** [comment]
This issue isn't relevant for the new version (we don't have anymore the "help" link on the menu). 

If it's an error please free to create a new issue on https://github.com/decidim/decidim/issues/new 

Closing this issue.
