### ISSUE TITLE
Sorting by "relevant" rather than by "controversial/pop but not enforceable"

### ISSUE THREAD

**Issue by AlfaSchz** [AjuntamentdeBarcelona/decidim.barcelona#787]
For proposals sorting, a **ranking system using an algorithm based on Wilson score confidence interval** would help rank up relevant proposals against controversial or pop but unenforceable ones. Implemented in the comments section, Wilson can also help maintaining discussions relevant.
Wilson does the maths to statistically balance the proportion of positive ratings with the uncertainty of a small number of observations.

Easy explanation on how and why Wilson here: [http://www.evanmiller.org/how-not-to-sort-by-average-rating.html](http://www.evanmiller.org/how-not-to-sort-by-average-rating.html)

It's what Reddit uses to sort its comments: [https://redditblog.com/2009/10/15/reddits-new-comment-sorting-system/](https://redditblog.com/2009/10/15/reddits-new-comment-sorting-system/)

Recommendation from: [https://github.com/AlfaSchz/decidim.barcelona/blob/master/informes/decidim.barcelona/Informe-Xnet-Decidim-Barcelona-oct-2016.md](https://github.com/AlfaSchz/decidim.barcelona/blob/master/informes/decidim.barcelona/Informe-Xnet-Decidim-Barcelona-oct-2016.md) (ES/CA)

**Comment by andreslucena** [comment]
Moved to new version https://github.com/decidim/decidim/issues/424
Closing this issue
