### ISSUE TITLE
Prevent duplicates ex-ante

### ISSUE THREAD

**Issue by AlfaSchz** [AjuntamentdeBarcelona/decidim.barcelona#788]
The implementation of a **technical functionality to prevent *ex-ante* duplicate proposals**. Before submitting their proposal, citizens would be shown other previous potentially equal or similar proposal. Like so, citizens can decide to not duplicate the proposal and instead support the existing one, and even contribute improving it.

An example of this kind of implementation can be seen in the users driven news aggregator [https://www.meneame.net/](https://www.meneame.net/) when submitting a news story. It is open source and the code can be found here: [https://github.com/gallir/Meneame](https://github.com/gallir/Meneame)

This kind of technology for searching similar contributions through semantic or keyword analysis can also be used as a tool for moderators to easily identify and prevent propaganda, spam and astroturfing attacks.

Recommendation from: [https://github.com/AlfaSchz/decidim.barcelona/blob/master/informes/decidim.barcelona/Informe-Xnet-Decidim-Barcelona-oct-2016.md])https://github.com/AlfaSchz/decidim.barcelona/blob/master/informes/decidim.barcelona/Informe-Xnet-Decidim-Barcelona-oct-2016.md) (ES/CA)

**Comment by josepjaume** [comment]
Hi!

Thank you very much - your insights on the matter are really appreciated. Decidim.barcelona is considered deprecated and we're moving the development to https://github.com/AjuntamentdeBarcelona/decidim . Would you mind replicating the issue there (along the others you just created)? We're actually rethinking much of this stuff in there.

Thanks!!

**Comment by AlfaSchz** [comment]
Sure!

**Comment by andreslucena** [comment]
Moved to new repo: https://github.com/decidim/decidim/issues/423 
Closing this issue
