### ISSUE TITLE
Implementation of an appeal process to the withdrawal of content

### ISSUE THREAD

**Issue by AlfaSchz** [AjuntamentdeBarcelona/decidim.barcelona#789]
For the sake of transparency, accountability and freedom of speech, an appeal process to the withdrawal of users' content should be put in place (both technically and along with the guidelines of the moderation and process itself).

Recommendation from: [https://github.com/AlfaSchz/decidim.barcelona/blob/master/informes/decidim.barcelona/Informe-Xnet-Decidim-Barcelona-oct-2016.md](https://github.com/AlfaSchz/decidim.barcelona/blob/master/informes/decidim.barcelona/Informe-Xnet-Decidim-Barcelona-oct-2016.md) (ES/CA)

**Comment by andreslucena** [comment]
It's been moved to the new version https://github.com/AjuntamentdeBarcelona/decidim.barcelona-legacy/issues/789 
Closing this issue
