### ISSUE TITLE
URL broken

### ISSUE THREAD

**Issue by JuanLinaresLanzman** [AjuntamentdeBarcelona/decidim.barcelona#790]
https://decidim.barcelona/pages/faq

**Comment by mrcasals** [comment]
Hi @JuanLi1979! This repo is for the old version of the website, the current one is found here:

https://github.com/AjuntamentdeBarcelona/decidim-barcelona

This issue is already tracked at https://github.com/AjuntamentdeBarcelona/decidim-barcelona/issues/33, can you close this one please? :)
